# --- !Ups

create table "CONTACT" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "NAME" varchar not null,
  "PNUMBER" varchar not null
);
INSERT INTO CONTACT (ID, NAME, PNUMBER) VALUES (1,'GadkiKostya','+79788216710');
INSERT INTO CONTACT (ID, NAME, PNUMBER) VALUES (2,'Denis','+79788222521');
# --- !Downs

drop table "people" if exists;
